#!/usr/bin/env bash

set -euo pipefail
shopt -s nullglob

cname="$1"

IFS=',' read -r -a features < <(./parse_features --feature-dir features --cname "$cname" features)

artifacts=("/mnt/builder-target/$cname-$COMMIT.tar" "/mnt/builder-target/$cname-$COMMIT.release" "/mnt/builder-target/$cname-$COMMIT.manifest")

for feature in "${features[@]}"; do
	for i in "features/$feature/"{image,convert}.*; do
		# get target artifact file extension, usually this is the image/convert script extension
		# except if the script extension is of the form filename.extA~extB in which case the artifact extension is .extA only
		extension="$(grep -E -o '(\.[a-z][a-zA-Z0-9\-_~]*)*$' <<< "$i")"
		artifacts+=("/mnt/builder-target/$cname-$COMMIT${extension%~*}")
	done
done

if [ "${#artifacts[@]}" = 3 ] && [ -n "$(./parse_features --feature-dir "features" --cname "$cname" platforms)" ]; then
	artifacts+=("/mnt/builder-target/$cname-$COMMIT.raw")
fi

echo "${artifacts[@]}"
